# timestamp
Header header
# FSR sensor value for the right foot (front left, front right, rear left, rear right) (kg)
float32[4] right_foot_fsr
# The total weight on the right foot (kg)
float32 right_foot_total
# Left foot center of pressure (x,y) in m
float32[2] LF_COP
# Left foot active error
int8 LF_Active_Error
# Left foot passive error
int8 LF_Passive_Error

# FSR sensor value for the right foot (front left, front right, rear left, rear right)
float32[4] left_foot_fsr
# The total weight on the left foot (kg)
float32 left_foot_total
# Right foot center of pressure (x,y) in m
float32[2] RF_COP
# Right foot active error
int8 RF_Active_Error
# Right foot passive error
int8 RF_Passive_Error
